### ISSUE TITLE
Have an option to paste a URL without linkifying it

### ISSUE THREAD

**Issue by hlashbrooke** [pento/linkify#10]
In some cases, all I want to do is paste a URL into a textarea and have the URL be the visible text, instead of having it turned into an `a` tag. It would be great if I could hold down an extra key while pasting (like `alt` or something) to make the link just paste as a raw URL instead of being linkified.

Would that be possible?

**Comment by hlashbrooke** [comment]
Would something like this work:

```
if(e.altKey) {
  return;
}
```

Apparently `altKey` is valid there, but I've never built a Chrome extension before and my JS skills are fairly average, so I'm not sure if that would work..

**Comment by pento** [comment]
Yep, that'll work. Let's do `e.shiftKey`, though, so it matches the "Paste and Match Style" command.

**Comment by pento** [comment]
As it turns out, this is a bit trickier than I expected. The `paste` event doesn't include keyboard information, nor does it have a flag for when "Paste and Match Style" is used.

There are ways to work around it, but they have their drawbacks:
- Have a listener to the `keyup` and `keydown` events, and maintain the state of the Shift key that way. This can pretty easily get out of sync, though, as the corresponding `keyup` event won't be triggered if the user presses Shift (triggering `keydown`), then switches windows before releasing Shift.
- Instead of listening for the `paste` event, listen for the `keydown` event, and duplicate the behaviour of pasting when the appropriate key combination is pressed. This is pretty hacky, may not work properly on all OSes, and doesn't take into account custom key combinations that could trigger `paste`. It also won't work with selecting "Paste and Match Style" from the Edit or right-click menus.

**Comment by hlashbrooke** [comment]
> As it turns out, this is a bit trickier than I expected.

Sounds about right for most 'simple' tasks 😛 

Those solutions all sound kind of hacky/volatile, so they're probably not ideal. It's a pity there isn't a way to check for which keys are currently being held down, like an `isKeyDown` method or something that you can use after the point where `keyDown` would have been triggered - someone should get on working out how to add that.

I'm probably horribly wrong here as my JS skillz are somewhat lacking, but is there not a global event object that you can access? So not just the object that is passed through the `paste` event, but something that works on a global scale. Like `window.event` or something like that? Grasping at straws I think, but it feels like something like that _should_ exist.

**Comment by pento** [comment]
So, there really isn't a good way to detect this. I think the best option is going to be to track the `keydown` event, and record whether Shift is pressed or not. Then, when the `paste` event lands, we can just check our flag.

Pros:

- Any custom paste shortcut works, as long as Shift is the "paste and match style" modifier.
- Holding down Shift while clicking the Paste menu item works.
- Very unlikely to get out of sync.

Cons:

- The "Paste and Match Style" menu item won't work.
- It might be possible to have a custom paste key combo that this doesn't work with.
