### ISSUE TITLE
Pasting a link into a blank area creates an anchor link

### ISSUE THREAD

**Issue by jonathanbossenger** [pento/linkify#146]
Only observed so far in Trello and GitHub, but when pasting a link into a blank text area, it creates a blank anchor link.

1. Create a new Trello card/GH Issue
2. Paste the link into a blank description
3. Creates the following output

```
<a href="https://example.com/link"></a>
```

Ideally, it should check if any text has been selected and only replace if there is some selected text.

P.S. I'm going to try and create a PR for this, mostly because I want to also contribute to making it support GDocs and Basecamp, and this is probably a "good first bug".

Also, nice work! 🎉

**Comment by pento** [comment]
Thanks for the bug report, @jonathanbossenger!

This is intended behaviour: pasting a URL without any text selected will create a blank link, and place your cursor inside of it, so you can continue typing immediately. If you just want to paste the plain URL, try holding down `Shift` when you paste (either `Ctrl`/`Cmd`+`Shift`+`V` or hold down `Shift` while pasting using the Edit or context menus). The idea of using the `Shift` modifier is that it matches the concept of how "Paste and Match Formatting" is used when pasting normal text.

It's worth noting that whilst this generally behaves correctly in Chrome, but Firefox seems to have a long term bug with using the keyboard shortcut when pasting into `textarea`s. 

And since you're using Trello, I've just released a version to produce Markdown links in Trello, instead of HTML. Firefox update is out now, the Chrome version will be delayed a little while they review the update. 🙂

**Comment by pento** [comment]
I'm going to close this issue, but feel free to open PRs for supporting other sites and services. 🙂

**Comment by jonathanbossenger** [comment]
Apologies, was off yesterday, so I didn't get a chance to reply. I'm seeing a bug on Ubuntu in Firefox where `Shift` + context + paste works as expected, but not the keyboard combo. That might be because I'm on Ubuntu, will keep testing. 

> but Firefox seems to have a long term bug with using the keyboard shortcut when pasting into textareas.

Apologies, I missed this, so probably that's the issue.

Would you be open to a PR for adding an option to the extension, that allows you to turn this behavior off if you prefer to be able to just paste links without needing to have text attached to them?

**Comment by pento** [comment]
Sure, PRs are always welcome! 

I haven't created an options screen yet, I'd recommend basing it off [this template](https://github.com/fregante/browser-extension-template).

**Comment by jonathanbossenger** [comment]
Perfect, thanks for the tip.

Created #147 to manage the eventual PR.
